name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: FM4SE-Exercise-1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Starter Code
        uses: actions/checkout@v2

      - name: Change permission
        run: chmod a+x lib/limboole-linux-*.exe

      - name: Execute tests
        run: curl -s https://gist.githubusercontent.com/soaibsafi/83347d08e781aa8153703db0221db90e/raw/603e9b2175c9797f64080e849cd3eedc7bb99b6c/tests.sh | bash -s
    
      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Display Java version
        run: java -version
      
      - name: Grading
        uses: education/autograding@v1
